# Generated by Django 3.1.1 on 2020-09-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoachExtra',
            new_name='CoachProfileExtra',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('profiles.profile',),
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('profiles.profile',),
        ),
    ]
