# Generated by Django 3.1.1 on 2020-09-19 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200918_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofileextra',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.coachprofile'),
        ),
    ]
