# Generated by Django 3.1.1 on 2020-09-24 06:39

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofileextra',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.coach_image_path),
        ),
        migrations.AddField(
            model_name='coachprofileextra',
            name='panel_image',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.coach_image_path),
        ),
    ]
