# Generated by Django 3.1.2 on 2020-10-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
