# Generated by Django 3.1.2 on 2020-10-16 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workoutbank', '0002_auto_20201015_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutitem',
            name='category',
        ),
        migrations.AddField(
            model_name='workoutcategory',
            name='workouts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workoutbank.workoutitem'),
            preserve_default=False,
        ),
    ]
