# Generated by Django 3.1.2 on 2020-10-16 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workoutbank', '0003_auto_20201016_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutcategory',
            name='workouts',
        ),
        migrations.AddField(
            model_name='workoutitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='workoutbank.workoutcategory'),
            preserve_default=False,
        ),
    ]
