# Generated by Django 3.1.2 on 2020-10-17 08:10

from django.db import migrations, models
import workoutbank.models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutbank', '0004_auto_20201016_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutcategory',
            name='image',
            field=models.ImageField(default='', upload_to=workoutbank.models.workout_cat_image_path, verbose_name='category image'),
        ),
    ]
