# Generated by Django 3.1.1 on 2020-09-24 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_auto_20200922_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client', to='accounts.client')),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='coach', to='accounts.coach')),
            ],
        ),
    ]
