# Generated by Django 3.1.1 on 2020-09-25 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sizes', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='size',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sizes.size'),
        ),
    ]
