# Generated by Django 3.1.1 on 2020-09-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_plan_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='food_nature',
            field=models.CharField(choices=[('VEGETARIAN', 'گیاه\u200cخوار'), ('NONVEGETARIAN', 'با خوردن گوشت مشکلی ندارم.')], default='NONVEGETARIAN', max_length=13),
        ),
    ]
