# Generated by Django 3.1.1 on 2020-09-25 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_images', '0001_initial'),
        ('plans', '0003_plan_food_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='client_images.clientimage'),
        ),
    ]
