# Generated by Django 3.1.1 on 2020-09-26 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_images', '0002_auto_20200925_1006'),
        ('plans', '0006_auto_20200926_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='client_images.clientimage'),
        ),
    ]
