# Generated by Django 3.1.1 on 2020-09-26 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200922_1532'),
        ('plans', '0009_auto_20200926_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_obj', to='accounts.client'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='coach_obj', to='accounts.coach'),
        ),
    ]
