# Generated by Django 3.1.1 on 2020-09-20 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_profile_user'),
        ('accounts', '0005_remove_account_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
