# Generated by Django 3.1.1 on 2020-09-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200922_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('COACH', 'Coach'), ('CLIENT', 'Client')], default='CLIENT', max_length=10, verbose_name='Type'),
        ),
    ]
