# Generated by Django 3.1.1 on 2020-09-25 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_auto_20200922_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=30)),
                ('weight', models.CharField(max_length=30)),
                ('neck', models.CharField(max_length=30)),
                ('arm', models.CharField(max_length=30)),
                ('wrist', models.CharField(max_length=30)),
                ('waist', models.CharField(max_length=30)),
                ('hamstring', models.CharField(max_length=30)),
                ('calf', models.CharField(max_length=30)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.client')),
            ],
        ),
    ]
