# Generated by Django 3.1.1 on 2020-09-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='chest',
            field=models.CharField(default=120, max_length=30),
            preserve_default=False,
        ),
    ]
