# Generated by Django 3.1.1 on 2020-09-26 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200922_1532'),
        ('sizes', '0002_size_chest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.client'),
        ),
    ]
