# Generated by Django 3.1.1 on 2020-09-25 10:06

import client_images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientimage',
            name='back',
            field=models.ImageField(upload_to=client_images.models.plan_image_upload_path, verbose_name='back image'),
        ),
        migrations.AlterField(
            model_name='clientimage',
            name='front',
            field=models.ImageField(upload_to=client_images.models.plan_image_upload_path, verbose_name='front image'),
        ),
        migrations.AlterField(
            model_name='clientimage',
            name='side',
            field=models.ImageField(upload_to=client_images.models.plan_image_upload_path, verbose_name='side image'),
        ),
    ]
